version: 0.2
env:
  variables:
    S3_BUCKET_FOR_ARTIFACT: ""
    TEMPLATE: ""
phases:
#   install:
#     commands:
#       - command
#       - command
  pre_build:
    commands:
      - sh ./test-script.sh
  build:
    commands:
      # - aws cloudformation package --template $TEMPLATE --s3-bucket $S3_BUCKET_FOR_ARTIFACT --output-template post-$TEMPLATE.yaml
      # - POST_TEMPLATE=post-${TEMPLATE}
      # - echo $POST_TEMPLATE
      - aws cloudformation package --template $TEMPLATE --s3-bucket $S3_BUCKET_FOR_ARTIFACT --output-template post-${TEMPLATE} --kms-key-id 'e163a727-71b7-4da7-bfdc-6e542b71fbbe'
  # post_build:
  #   commands:
  #     - command
  #     - command
# artifacts:
  # files:
    # - post-${TEMPLATE}.yaml
    # - location
  # discard-paths: yes
  # base-directory: location