AWSTemplateFormatVersion: "2010-09-09"
Resources:
  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # Parameters:
        TemplateURL: ./
      #   DomainName: !Ref DomainName
      # TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/toolings/pipelines/infrastructure/service-roles.yaml
  